"""
Pydantic v2 models for GitHub webhook payloads and audit results.
All fields are strictly validated — unknown fields raise validation errors.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, HttpUrl, field_validator, model_validator


# ─────────────────────────────────────────────────────────────
# GitHub Payload Models
# ─────────────────────────────────────────────────────────────

class PRAction(str, Enum):
    OPENED = "opened"
    SYNCHRONIZE = "synchronize"
    REOPENED = "reopened"
    CLOSED = "closed"
    LABELED = "labeled"
    UNLABELED = "unlabeled"
    READY_FOR_REVIEW = "ready_for_review"
    REVIEW_REQUESTED = "review_requested"


class GitHubUser(BaseModel):
    model_config = ConfigDict(extra="ignore")

    login: str
    id: int
    type: str = "User"
    html_url: str | None = None


class GitHubCommitRef(BaseModel):
    model_config = ConfigDict(extra="ignore")

    sha: str = Field(..., min_length=7, max_length=40)
    ref: str  # branch name
    label: str | None = None

    @field_validator("sha")
    @classmethod
    def sha_must_be_hex(cls, v: str) -> str:
        if not all(c in "0123456789abcdefABCDEF" for c in v):
            raise ValueError(f"SHA must be hexadecimal, got: {v}")
        return v.lower()


class GitHubRepository(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: int
    name: str
    full_name: str  # "owner/repo"
    private: bool
    html_url: str
    clone_url: str
    default_branch: str = "main"
    language: str | None = None

    @field_validator("full_name")
    @classmethod
    def full_name_must_have_owner(cls, v: str) -> str:
        if "/" not in v:
            raise ValueError(f"Repository full_name must be 'owner/repo', got: {v}")
        return v


class GitHubPullRequest(BaseModel):
    model_config = ConfigDict(extra="ignore")

    number: int = Field(..., gt=0)
    title: str = Field(..., min_length=1, max_length=256)
    state: str
    draft: bool = False
    mergeable: bool | None = None
    additions: int = 0
    deletions: int = 0
    changed_files: int = 0
    html_url: str
    diff_url: str
    head: GitHubCommitRef
    base: GitHubCommitRef
    user: GitHubUser
    created_at: datetime
    updated_at: datetime

    @model_validator(mode="after")
    def reject_draft_prs(self) -> "GitHubPullRequest":
        # Draft PRs are not audited by default
        return self


class GitHubPRPayload(BaseModel):
    """
    Root webhook payload for 'pull_request' events.
    Strictly validated with Pydantic v2.
    """
    model_config = ConfigDict(extra="ignore", frozen=True)

    action: PRAction
    number: int = Field(..., gt=0)
    pull_request: GitHubPullRequest
    repository: GitHubRepository
    sender: GitHubUser
    installation: dict[str, Any] | None = None  # GitHub App installation context


# ─────────────────────────────────────────────────────────────
# Audit Domain Models
# ─────────────────────────────────────────────────────────────

class Severity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class FindingCategory(str, Enum):
    SECURITY = "SECURITY"
    QUALITY = "QUALITY"
    DEPENDENCY = "DEPENDENCY"
    PATCH = "PATCH"


class AuditStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PASSED = "PASSED"
    BLOCKED = "BLOCKED"
    ERROR = "ERROR"
    OVERRIDDEN = "OVERRIDDEN"


class CodeLocation(BaseModel):
    """Precise location of a finding in the diff."""
    model_config = ConfigDict(frozen=True)

    file: str
    line_start: int
    line_end: int | None = None
    code_snippet: str = Field(..., description="Exact code excerpt that triggered the finding")


class ToolEvidence(BaseModel):
    """Raw output from the security/quality tool that generated this finding."""
    model_config = ConfigDict(frozen=True)

    tool_name: str
    tool_version: str | None = None
    raw_output: str = Field(..., description="Raw tool output excerpt (max 2000 chars)")
    command_run: str | None = Field(None, description="Exact CLI command that was executed")

    @field_validator("raw_output")
    @classmethod
    def truncate_raw_output(cls, v: str) -> str:
        return v[:2000] if len(v) > 2000 else v


class PatchSuggestion(BaseModel):
    """Executable patch generated by Agent C."""
    model_config = ConfigDict(frozen=True)

    patch_diff: str = Field(..., description="Unified diff format patch")
    test_code: str = Field(..., description="pytest test code that validates the fix")
    test_passed: bool = False
    coverage_pct: float | None = None
    sandbox_run_id: str | None = None
    confidence_score: float = Field(0.0, ge=0.0, le=1.0)


class Finding(BaseModel):
    """
    A single auditor finding. Enforces zero-hallucination fields:
    rule_id, tool_evidence, and code_location are ALL required.
    """
    model_config = ConfigDict(frozen=True)

    finding_id: str
    rule_id: str = Field(..., description="Must reference a rule ID from security-rules.spec")
    agent_id: str = Field(..., description="Which agent produced this: agent_a, agent_b, agent_c")
    category: FindingCategory
    severity: Severity
    title: str
    description: str
    owasp_category: str | None = None
    location: CodeLocation
    evidence: ToolEvidence
    patch: PatchSuggestion | None = None
    suppressed: bool = False
    suppression_reason: str | None = None


class AgentMetrics(BaseModel):
    """Per-agent execution telemetry."""
    model_config = ConfigDict(frozen=True)

    agent_id: str
    started_at: datetime
    completed_at: datetime | None = None
    duration_seconds: float | None = None
    files_scanned: int = 0
    lines_analyzed: int = 0
    tool_calls: list[dict[str, Any]] = Field(default_factory=list)
    error: str | None = None


class ComplianceReport(BaseModel):
    """OWASP Top 10 compliance summary attached to the PR."""
    model_config = ConfigDict(frozen=True)

    generated_at: datetime
    pr_number: int
    repo: str
    head_sha: str
    owasp_findings: dict[str, list[str]] = Field(
        default_factory=dict,
        description="Mapping of OWASP category to list of finding IDs"
    )
    overall_risk_score: float = Field(0.0, ge=0.0, le=10.0)
    markdown_report: str = ""


class AuditResult(BaseModel):
    """Complete result of one audit pipeline run."""
    model_config = ConfigDict(frozen=True)

    audit_id: str
    pr_number: int
    repo_full_name: str
    head_sha: str
    delivery_id: str
    overall_status: AuditStatus
    started_at: datetime
    completed_at: datetime | None = None
    findings: list[Finding] = Field(default_factory=list)
    agent_metrics: list[AgentMetrics] = Field(default_factory=list)
    compliance_report: ComplianceReport | None = None
    original_payload: GitHubPRPayload | None = None
    override_reason: str | None = None
    error_detail: str | None = None

    @property
    def critical_count(self) -> int:
        return sum(1 for f in self.findings if f.severity == Severity.CRITICAL and not f.suppressed)

    @property
    def high_count(self) -> int:
        return sum(1 for f in self.findings if f.severity == Severity.HIGH and not f.suppressed)

    @property
    def is_blocked(self) -> bool:
        return self.overall_status == AuditStatus.BLOCKED


class WebhookEvent(BaseModel):
    """Internal record of a received webhook event."""
    model_config = ConfigDict(frozen=True)

    event_id: str
    event_type: str
    delivery_id: str
    received_at: datetime
    audit_id: str | None = None
